version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: ./WebApi/Dockerfile
    container_name: currency_api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqlserver;Database=CurrencyTrackerDb;User=sa;Password=YourStrong!Passw0rd;
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5000:8080"
       
#  worker:
#    build:
#      context: .
#      dockerfile: src/Worker/Dockerfile
#    container_name: currency_worker
#    depends_on:
#      - sqlserver
#    environment:
#      - ConnectionStrings__Default=Server=sqlserver;Database=CurrencyTrackerDb;User=sa;Password=YourStrong!Passw0rd;

#  ui:
#    build:
#      context: ui
#      dockerfile: Dockerfile
#    container_name: currency_ui
#    ports:
#      - "8080:80"
#    depends_on:
#      - api

volumes:
  sql_data:
